### ISSUE TITLE
Fix Volunteer Page

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand.github.io#49]
**Seems our volunteer page got an iframe but the text died is put under get-involved**

Saving the world should be fun, rewarding and directly benefit everyone involved.

Contributing to this movement is an excellent way to gain real-life experience and pad your resume. 

Choosing to advance your skills here can make a tremendous impact on lives and cool the earth. 

See our

"General Skills (Join The Team)"

https://docs.google.com/forms/d/e/1FAIpQLSdK_Db9cySVtL-QEQZMV7AC4VFrTFBMwKN15qPB8I9szme63w/viewform?usp=sf_link

"Tech Skills (Join The Tech Team)"

https://docs.google.com/forms/d/e/1FAIpQLSe61HDJKVH16vtTxhXpbwCH-wTVN1e6XoVU1riWjJ-ne5SIiA/viewform?usp=sf_link

For Development: https://github.com/Greenstand

You can also send an to info@greenstand.org

No time to help build it - support the Team (Donate)

**Comment by sebastiangaertner** [comment]
produces this error
Refused to display 'https://github.com/Greenstand/treetracker-android/graphs/contributors' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
read (if you want to...)
https://github.com/cypress-io/cypress/issues/1555
